# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 cubestudio-dev <cubestudio@qq.com>
# Open Cube OS configuration
# Update check URL (HTTP or HTTPS)
update_url=https://cubestudio-dev.github.io/OpenCubeOS/update.json

# Update package base URL (WP-10u, HTTP or HTTPS)
package_url=https://github.com/cubestudio-dev/OpenCubeOS/releases/latest

# Auto check on boot (yes / no)
auto_check=no

# Enable online system update (yes / no)
online_update=yes
