/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2026 cubestudio-dev <cubestudio@qq.com> */
/* Open Cube OS - WP-10d-pre (rule-9 system self-sufficiency fix)
 * File: kernel/grub_boot_data.h
 * Purpose: interface to the build-time embedded GRUB boot loader and the
 *          running kernel's own ELF image (see tools/embed_grub.py).
 *
 * The `abdisk`, `install` and `grub-install` shell commands use these
 * blobs to partition a disk, copy the system onto it and write a BIOS
 * boot loader - all from inside the OS, with no host tools:
 *
 *   oc_grub_boot_img    512-byte GRUB MBR boot code (i386-pc boot.img).
 *                       grub-install patches the core-start LBA (0x5C)
 *                       and preserves the on-disk partition table area.
 *   oc_grub_core_img    grub-mkimage core.img: BIOS disk driver, MBR/GPT
 *                       partition support, FAT, multiboot2, search, an
 *                       embedded early config (find /boot/grub/grub.cfg)
 *                       and the modules the on-disk grub.cfg needs.
 *                       Written to the MBR gap (LBA 1..) or, on GPT
 *                       disks, to the BIOS boot partition.
 *
 * The kernel ELF payload is NOT embedded here: the grub.cfg files attach
 * the booting kernel as a multiboot2 module ("module2 ... self") and
 * disk_setup.c copies that module onto the target disk (see
 * oc_mb2_get_kernel_self() in multiboot2.h).
 */
#ifndef OC_GRUB_BOOT_DATA_H
#define OC_GRUB_BOOT_DATA_H

#include "types.h"

/* Strong extern declarations.  Every kernel build links exactly one
 * definition set:
 *   - stage 1 (opencube_base.elf): kernel/grub_boot_stub.c (zero lengths)
 *   - stage 2 (opencube.elf):      kernel/generated/grub_boot_data.c
 *     (real GRUB boot/core images, generated by tools/embed_grub.py)
 * disk_setup.c checks the *_len symbols for 0 before use, so a stage-1
 * kernel refuses abdisk/install/grub-install instead of writing garbage.
 */
extern const unsigned char oc_grub_boot_img[];
extern const unsigned char oc_grub_core_img[];

extern const unsigned int oc_grub_boot_img_len;
extern const unsigned int oc_grub_core_img_len;

#endif /* OC_GRUB_BOOT_DATA_H */
