/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2026 cubestudio-dev <cubestudio@qq.com> */
/*
 * Open Cube OS - WP-10u
 * File: kernel/update_test_cmds.c
 * Purpose: shell test suite for the in-system update (A/B partitions).
 *
 * Commands (registered in kmain.c):
 *   update_pkg_test       gzip/DEFLATE + tar unit tests (no network)
 *   update_check_test     manifest check incl. package fields (network)
 *   update_download_test  download the package (network + package_url)
 *   update_verify_test    SHA256 verification + negative case
 *   update_install_test   install the package into slot B (A/B disk)
 *   update_rollback_test  boot-flag switching + rollback
 *   update_local_test     offline flow through cmd_update --local
 *   update_status_test    oc_update_get_status field coverage
 *   ab_partition_test     A/B disk discovery, partition devices, mounts
 *   real_update_test      end-to-end phase 1 (download..set_boot); the
 *                         reboot + slot-B verification is the phase 2
 *                         driver sequence in the delivery report
 *
 * Every case prints its expected/actual values and PASS/FAIL.
 */
#include "update_test_cmds.h"
#include "ab_update.h"
#include "update.h"
#include "config.h"
#include "blk.h"
#include "vfs.h"
#include "gzip.h"
#include "tar.h"
#include "crypto.h"
#include "heap.h"
#include "console.h"
#include "shell.h"
#include "string.h"

#include <stdint.h>

/* expected sizes for the embedded vectors */
#define GZV_PAYLOAD_LEN 1280
#define GZV_TINY_LEN    6
static const char *GZV_TINY_EXPECTED = "ABCDEF";

/* ---- test vectors (generated by tools/gen_gzip_vectors.py) ---------- */
#include "update_test_vectors.inc"

/* ---- helpers -------------------------------------------------------- */

static int t_pass = 0, t_total = 0;

static void case_begin(const char *name) {
    oc_console_puts("[");
    oc_console_puts(name);
    oc_console_puts("] ");
}

static void case_result(int ok) {
    t_total++;
    if (ok) t_pass++;
    oc_console_puts(ok ? "PASS\n" : "FAIL\n");
}

static void case_info(const char *label, long value) {
    char info[80];
    char num[16];
    oc_strcpy(info, label);
    if (value < 0) {
        oc_strcat(info, "-");
        oc_u64_to_str((u64)(-value), num);
    } else {
        oc_u64_to_str((u64)value, num);
    }
    oc_strcat(info, num);
    oc_console_puts(info);
    oc_console_puts(" ");
}

/* accumulate sink for streaming cases (file-scope: C has no closures) */
static u8  *g_acc_out;
static int  g_acc_len;
static int  g_acc_cap;

static int acc_sink(void *ctx, const u8 *data, int n) {
    (void)ctx;
    if (g_acc_len + n > g_acc_cap) return -1;
    for (int i = 0; i < n; i++) g_acc_out[g_acc_len++] = data[i];
    return 0;
}

/* ---- shared package-file location ------------------------------------ */

static const char *downloaded_package_path(void) {
    vfs_stat_t st;
    if (vfs_stat(OC_UPDATE_PKG_PATH, &st) == 0 && st.size > 0)
        return OC_UPDATE_PKG_PATH;
    if (vfs_stat(OC_UPDATE_PKG_TMP, &st) == 0 && st.size > 0)
        return OC_UPDATE_PKG_TMP;
    return NULL;
}

/* ---- ustar header builder (tar parser unit cases) -------------------- */

static void tar_put_octal(char *dst, int width, u64 v) {
    char tmp[24];
    int i = 0;
    if (v == 0) tmp[i++] = '0';
    while (v > 0) { tmp[i++] = (char)('0' + (v & 7)); v >>= 3; }
    int p = 0;
    for (int z = 0; z < width - 1 - i; z++) dst[p++] = '0';
    while (i > 0) dst[p++] = tmp[--i];
    dst[p] = 0;
}

static void tar_build_header(u8 *blk, const char *name, u64 size, char type) {
    oc_memset(blk, 0, 512);
    oc_strncpy((char *)blk, name, 99);
    oc_memcpy(blk + 100, "0000644\0", 8);
    oc_memcpy(blk + 108, "0000000\0", 8);
    oc_memcpy(blk + 116, "0000000\0", 8);
    char sz[13];
    tar_put_octal(sz, 12, size);
    oc_memcpy(blk + 124, sz, 12);
    oc_memcpy(blk + 136, "00000000000\0", 12);
    oc_memset(blk + 148, ' ', 8);
    blk[156] = (u8)type;
    oc_memcpy(blk + 257, "ustar\0", 6);
    oc_memcpy(blk + 263, "00", 2);
    u32 sum = 0;
    for (int i = 0; i < 512; i++) sum += blk[i];
    char cs[9];
    tar_put_octal(cs, 8, sum);
    oc_memcpy(blk + 148, cs, 7);
    blk[155] = 0;
}

typedef struct {
    char   name[128];
    u64    size;
    u8     data[256];
    int    files;
} tar_acc_t;

static int tar_acc_cb(void *ctx, const char *path, int type, u64 size,
                      const u8 *data, int len) {
    tar_acc_t *a = (tar_acc_t *)ctx;
    if (type == OC_TAR_DIR) return 0;
    if (data == NULL && len == 0) return 0;      /* final slice */
    oc_strncpy(a->name, path, sizeof(a->name) - 1);
    a->size = size;
    a->files++;
    if (data && len <= (int)sizeof(a->data)) {
        oc_memcpy(a->data, data, len);
    }
    return 0;
}

/* ==================================================================== */
/* update_pkg_test: gzip/DEFLATE + tar unit tests                        */
/* ==================================================================== */

int cmd_update_pkg_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_pkg_test] gzip/DEFLATE + tar unit tests\n");

    u8 *out = (u8 *)kmalloc(GZV_PAYLOAD_LEN + 64);
    if (!out) {
        oc_console_puts("[update_pkg_test] out of memory\n");
        return 1;
    }

    /* 1..7: one-shot gunzip over every block type / header option */
    {
        int n = oc_gunzip(GZV_stored_GZ, (int)sizeof(GZV_stored_GZ),
                          out, GZV_PAYLOAD_LEN + 64);
        case_begin("gunzip stored block");
        int ok = (n == GZV_PAYLOAD_LEN &&
                  oc_memcmp(out, GZV_PAYLOAD_EXPECTED, GZV_PAYLOAD_LEN) == 0);
        case_info("exp=1280 got=", n);
        case_result(ok);
    }
    {
        int n = oc_gunzip(GZV_fixed_GZ, (int)sizeof(GZV_fixed_GZ),
                          out, GZV_PAYLOAD_LEN + 64);
        case_begin("gunzip fixed huffman block");
        int ok = (n == GZV_PAYLOAD_LEN &&
                  oc_memcmp(out, GZV_PAYLOAD_EXPECTED, GZV_PAYLOAD_LEN) == 0);
        case_info("exp=1280 got=", n);
        case_result(ok);
    }
    {
        int n = oc_gunzip(GZV_dynamic_GZ, (int)sizeof(GZV_dynamic_GZ),
                          out, GZV_PAYLOAD_LEN + 64);
        case_begin("gunzip dynamic huffman block");
        int ok = (n == GZV_PAYLOAD_LEN &&
                  oc_memcmp(out, GZV_PAYLOAD_EXPECTED, GZV_PAYLOAD_LEN) == 0);
        case_info("exp=1280 got=", n);
        case_result(ok);
    }
    {
        int n = oc_gunzip(GZV_tiny_GZ, (int)sizeof(GZV_tiny_GZ), out, 64);
        case_begin("gunzip tiny (no matches)");
        int ok = (n == GZV_TINY_LEN &&
                  oc_memcmp(out, GZV_TINY_EXPECTED, GZV_TINY_LEN) == 0);
        case_info("exp=6 got=", n);
        case_result(ok);
    }
    {
        int n = oc_gunzip(GZV_fname_GZ, (int)sizeof(GZV_fname_GZ),
                          out, GZV_PAYLOAD_LEN + 64);
        case_begin("gzip header FNAME");
        case_info("exp=1280 got=", n);
        case_result(n == GZV_PAYLOAD_LEN);
    }
    {
        int n = oc_gunzip(GZV_fextra_GZ, (int)sizeof(GZV_fextra_GZ),
                          out, GZV_PAYLOAD_LEN + 64);
        case_begin("gzip header FEXTRA");
        case_info("exp=1280 got=", n);
        case_result(n == GZV_PAYLOAD_LEN);
    }
    {
        int n = oc_gunzip(GZV_both_GZ, (int)sizeof(GZV_both_GZ),
                          out, GZV_PAYLOAD_LEN + 64);
        case_begin("gzip header FEXTRA+FNAME");
        case_info("exp=1280 got=", n);
        case_result(n == GZV_PAYLOAD_LEN);
    }
    kfree(out);

    /* 8: corrupted CRC must fail */
    {
        case_begin("corrupted CRC32 rejected");
        u8 *out2 = (u8 *)kmalloc(8192);
        int n = oc_gunzip(GZV_BCRC_GZ, (int)sizeof(GZV_BCRC_GZ),
                          out2, 8192);
        kfree(out2);
        case_result(n == OC_GZIP_ERR_CRC);
    }
    /* 9: truncated stream must fail */
    {
        case_begin("truncated stream rejected");
        u8 out2[64];
        int n = oc_gunzip(GZV_TRUNC_GZ, (int)sizeof(GZV_TRUNC_GZ),
                          out2, (int)sizeof(out2));
        case_result(n < 0);
    }
    /* 10: chunked streaming feed (1-byte chunks, resume coverage) */
    {
        g_acc_out = (u8 *)kmalloc(GZV_PAYLOAD_LEN + 64);
        g_acc_len = 0;
        g_acc_cap = GZV_PAYLOAD_LEN + 64;
        oc_gzip_t *g = (oc_gzip_t *)kmalloc(sizeof(oc_gzip_t));
        oc_memset(g, 0, sizeof(*g));
        case_begin("streaming resume (1-byte chunks)");
        int okr = (oc_gzip_init(g, acc_sink, NULL) == 0);
        for (int i = 0; okr && i < (int)sizeof(GZV_dynamic_GZ); i++) {
            if (oc_gzip_feed(g, &GZV_dynamic_GZ[i], 1) != 0) { okr = 0; break; }
        }
        if (okr) okr = (oc_gzip_finish(g) == 0);
        if (okr) okr = (g_acc_len == GZV_PAYLOAD_LEN);
        if (okr) okr = (oc_memcmp(g_acc_out, GZV_PAYLOAD_EXPECTED,
                                  GZV_PAYLOAD_LEN) == 0);
        case_info("out=", g_acc_len);
        kfree(g);
        kfree(g_acc_out);
        g_acc_out = NULL;
        case_result(okr);
    }
    /* 11: tar parser roundtrip */
    {
        case_begin("ustar parse (name/size/content)");
        u8 *stream = (u8 *)kmalloc(512 * 5);
        oc_memset(stream, 0, 512 * 5);
        tar_build_header(stream, "etc/opencube.conf", 11, '0');
        oc_memcpy(stream + 512, "HELLO-TAR!\0", 11);
        /* trailing two zero end blocks are already zero */
        tar_acc_t acc;
        oc_memset(&acc, 0, sizeof(acc));
        oc_tar_t *t = oc_tar_open(tar_acc_cb, &acc);
        int okt = (t != NULL);
        if (okt) {
            int total = 512 * 5;
            int pos = 0;
            int rc = 0;
            while (pos < total) {
                int take = 100;               /* odd chunks: block assembler */
                if (pos + take > total) take = total - pos;
                rc = oc_tar_feed(t, stream + pos, take);
                if (rc != 0) break;
                pos += take;
            }
            if (rc == 0) rc = oc_tar_finish(t);
            okt = (rc == 0);
        }
        if (okt) okt = (acc.files == 1 &&
                        oc_strcmp(acc.name, "etc/opencube.conf") == 0 &&
                        acc.size == 11 &&
                        oc_strcmp((char *)acc.data, "HELLO-TAR!") == 0);
        char info[96];
        oc_strcpy(info, "files=");
        char num[12];
        oc_u64_to_str((u64)acc.files, num);
        oc_strcat(info, num);
        oc_strcat(info, " name=");
        oc_strcat(info, acc.name);
        oc_console_puts(info);
        oc_console_puts(" ");
        if (t) oc_tar_close(t);
        kfree(stream);
        case_result(okt);
    }
    /* 12: tar checksum corruption rejected */
    {
        case_begin("ustar bad checksum rejected");
        u8 *stream = (u8 *)kmalloc(512 * 4);
        oc_memset(stream, 0, 512 * 4);
        tar_build_header(stream, "x", 0, '0');
        stream[148] ^= 0x01;                       /* corrupt checksum */
        tar_acc_t acc;
        oc_memset(&acc, 0, sizeof(acc));
        oc_tar_t *t = oc_tar_open(tar_acc_cb, &acc);
        int rc = t ? oc_tar_feed(t, stream, 512 * 4) : OC_TAR_ERR_ARGS;
        if (t) oc_tar_close(t);
        kfree(stream);
        case_result(rc == OC_TAR_ERR_CSUM);
    }

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_pkg_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* ab_partition_test: A/B disk discovery + partition devices + mounts    */
/* ==================================================================== */

int cmd_ab_partition_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[ab_partition_test] A/B disk + slots\n");

    /* 1. partition devices registered */
    case_begin("partition devices hdap1..p4");
    int all_devs = 1;
    for (int i = 1; i <= 4; i++) {
        char name[12];
        oc_strcpy(name, "hdap");
        char num[4];
        oc_u64_to_str((u64)i, num);
        oc_strcat(name, num);
        if (blk_find_device(name) < 0) { all_devs = 0; break; }
    }
    case_result(all_devs);

    /* 2. slot mounts */
    case_begin("slot mounts /ab/boot /ab/a /ab/b /data");
    vfs_stat_t st;
    int mounts_ok = (vfs_stat("/ab/boot", &st) == 0 &&
                     vfs_stat("/ab/a", &st) == 0 &&
                     vfs_stat("/ab/b", &st) == 0 &&
                     vfs_stat("/data", &st) == 0);
    case_result(mounts_ok);

    /* 3. partition device reads the slot-A FAT32 boot sector */
    case_begin("hdap2 boot sector (FAT32 BPB)");
    int bpb_ok = 0;
    {
        int idx = blk_find_device("hdap2");
        if (idx >= 0) {
            u8 sec[512];
            if (blk_read_sectors(idx, 0, 1, sec) == 0) {
                u16 bps = (u16)(sec[11] | (sec[12] << 8));
                u8 spc = sec[13];
                bpb_ok = (bps == 512 && spc > 0 &&
                          sec[510] == 0x55 && sec[511] == 0xAA);
            }
        }
    }
    case_result(bpb_ok);

    /* 4. current boot slot is a known value */
    case_begin("boot slot known (A/B/ISO)");
    int slot = oc_ab_current_slot();
    int slot_ok = (slot == OC_AB_SLOT_A || slot == OC_AB_SLOT_B ||
                   slot == OC_AB_SLOT_ISO);
    char sline[64];
    oc_strcpy(sline, "slot=");
    oc_strcat(sline, oc_ab_slot_name(slot));
    oc_console_puts(sline);
    oc_console_puts(" ");
    case_result(slot_ok);

    /* 5. flags partition reachable + flags readable */
    case_begin("boot flags readable");
    int nb = 0, okb = 0, bfb = 0;
    int flags_ok = (oc_ab_read_flags(&nb, &okb, &bfb) == 0);
    char fline[96];
    oc_strcpy(fline, "next_B=");
    oc_strcat(fline, nb ? "yes" : "no");
    oc_strcat(fline, " ok_B=");
    oc_strcat(fline, okb ? "yes" : "no");
    oc_strcat(fline, " bootfail_B=");
    oc_strcat(fline, bfb ? "yes" : "no");
    oc_console_puts(fline);
    oc_console_puts(" ");
    case_result(flags_ok);

    /* 6. write/read/delete roundtrip through set_boot + rollback */
    case_begin("set_boot(B) -> flags -> rollback clears");
    int rt_ok = 0;
    if (oc_update_set_boot("B") == 0) {
        int nb2 = 0, okb2 = 0, bfb2 = 0;
        if (oc_ab_read_flags(&nb2, &okb2, &bfb2) == 0 &&
            nb2 == 1 && okb2 == 0 && bfb2 == 0) {
            if (oc_update_rollback() == 0) {
                int nb3 = 0, okb3 = 0, bfb3 = 0;
                if (oc_ab_read_flags(&nb3, &okb3, &bfb3) == 0 &&
                    nb3 == 0 && okb3 == 0)
                    rt_ok = 1;
            }
        }
    }
    case_result(rt_ok);

    /* 7. invalid slot rejected */
    case_begin("set_boot(X) rejected");
    case_result(oc_update_set_boot("X") == OC_UPDATE_E_SLOT);

    char line[64];
    char num[12];
    oc_strcpy(line, "[ab_partition_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_check_test: manifest check with package fields                 */
/* ==================================================================== */

int cmd_update_check_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_check_test] package manifest check\n");

    /* 1. json_uint unit: package_size parsing */
    {
        case_begin("json_uint parses package_size");
        u64 v = 0;
        static const char *doc =
            "{\"version\":\"V\",\"package_size\":10485760}";
        int rc = oc_update_json_uint(doc, "package_size", &v);
        case_result(rc == 0 && v == 10485760u);
    }
    /* 2. json_uint unit: non-number rejected */
    {
        case_begin("json_uint rejects non-number");
        u64 v = 99;
        static const char *doc =
            "{\"version\":\"V\",\"package_size\":\"big\"}";
        int rc = oc_update_json_uint(doc, "package_size", &v);
        case_result(rc != 0);
    }
    /* 3. live manifest check (requires the network + update_url) */
    {
        case_begin("live check_pkg (OK/NEW)");
        oc_update_pkg_info_t pkg;
        int rc = oc_update_check_pkg(&pkg);
        int ok = (rc == OC_UPDATE_OK || rc == OC_UPDATE_NEW);
        oc_console_puts("rc=");
        char num[8];
        oc_u64_to_str((u64)rc, num);
        oc_console_puts(num);
        oc_console_puts(" version=");
        oc_console_puts(pkg.info.version);
        oc_console_puts(" ");
        case_result(ok);
    }
    /* 4. package fields present (server must ship them) */
    {
        case_begin("manifest has package fields");
        oc_update_pkg_info_t pkg;
        int rc = oc_update_check_pkg(&pkg);
        int ok = ((rc == OC_UPDATE_OK || rc == OC_UPDATE_NEW) &&
                  pkg.have_package);
        oc_console_puts("url=");
        oc_console_puts(pkg.package_url);
        oc_console_puts(" size=");
        char num[16];
        oc_u64_to_str(pkg.package_size, num);
        oc_console_puts(num);
        oc_console_puts(" ");
        case_result(ok);
    }

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_check_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_download_test                                                  */
/* ==================================================================== */

int cmd_update_download_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_download_test] streaming package download\n");

    /* 1. manifest check first (fills package_url) */
    case_begin("manifest check");
    oc_update_pkg_info_t pkg;
    int rc = oc_update_check_pkg(&pkg);
    int ok = ((rc == OC_UPDATE_OK || rc == OC_UPDATE_NEW) && pkg.have_package);
    case_result(ok);
    if (!ok) {
        oc_console_puts("[update_download_test] need package_url "
                        "(run on a network with the update server)\n");
        return 1;
    }

    /* 2. download to /data (or /tmp; args overrides the target path) */
    const char *path = OC_UPDATE_PKG_PATH;
    vfs_stat_t st;
    if (args && args[0]) {
        path = args;
    } else if (vfs_stat("/data", &st) != 0) {
        path = OC_UPDATE_PKG_TMP;
    }

    case_begin("download package");
    oc_console_puts("url=");
    oc_console_puts(pkg.package_url);
    oc_console_puts("\n");
    int n = oc_update_download(pkg.package_url, path);
    case_info("bytes=", n);
    case_result(n > 0);

    /* 3. size matches the manifest */
    case_begin("size matches package_size");
    int size_ok = 0;
    if (n > 0 && vfs_stat(path, &st) == 0) {
        size_ok = (st.size == (u64)n &&
                   (pkg.package_size == 0 || st.size == pkg.package_size));
    }
    case_result(size_ok);

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_download_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_verify_test                                                    */
/* ==================================================================== */

int cmd_update_verify_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_verify_test] SHA256 verification\n");

    const char *path = downloaded_package_path();
    case_begin("package file present");
    case_result(path != NULL);
    if (!path) {
        oc_console_puts("[update_verify_test] run update_download_test "
                        "first\n");
        return 1;
    }

    oc_update_pkg_info_t pkg;
    int rc = oc_update_check_pkg(&pkg);
    case_begin("manifest check");
    case_result(rc == OC_UPDATE_OK || rc == OC_UPDATE_NEW);

    case_begin("verify against manifest sha256");
    rc = oc_update_verify(path, pkg.package_sha256);
    case_result(rc == 0);

    case_begin("wrong sha256 rejected");
    {
        char wrong[80];
        oc_strcpy(wrong, pkg.package_sha256);
        wrong[0] = (wrong[0] == '0') ? '1' : '0';
        int rc2 = oc_update_verify(path, wrong);
        case_result(rc2 == OC_UPDATE_E_SHA);
    }

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_verify_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_install_test                                                   */
/* ==================================================================== */

int cmd_update_install_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_install_test] install package into slot B\n");

    case_begin("A/B disk present");
    int ab = oc_ab_flags_ready();
    case_result(ab);
    if (!ab) {
        oc_console_puts("[update_install_test] attach the A/B disk "
                        "(build/abdisk.img)\n");
        return 1;
    }

    const char *path = downloaded_package_path();
    case_begin("package file present");
    case_result(path != NULL);
    if (!path) return 1;

    case_begin("install into slot B");
    int rc = oc_update_install(path, "B");
    case_result(rc == 0);

    case_begin("kernel installed at /ab/b/boot/opencube.elf");
    vfs_stat_t st;
    case_result(vfs_stat("/ab/b/boot/opencube.elf", &st) == 0 &&
                st.size > 0);

    case_begin("config installed at /ab/b/etc/opencube.conf");
    case_result(vfs_stat("/ab/b/etc/opencube.conf", &st) == 0);

    case_begin("grub.cfg mirrored to flags partition");
    case_result(vfs_stat("/ab/boot/boot/grub/grub.cfg", &st) == 0);

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_install_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_rollback_test                                                  */
/* ==================================================================== */

int cmd_update_rollback_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_rollback_test] boot flags + rollback\n");

    case_begin("A/B disk present");
    int ab = oc_ab_flags_ready();
    case_result(ab);
    if (!ab) return 1;

    case_begin("set_boot(B) writes next_B");
    int ok = 0;
    if (oc_update_set_boot("B") == 0) {
        int nb = 0, okb = 0, bfb = 0;
        ok = (oc_ab_read_flags(&nb, &okb, &bfb) == 0 && nb == 1);
    }
    case_result(ok);

    case_begin("rollback clears next_B/ok_B");
    ok = 0;
    if (oc_update_rollback() == 0) {
        int nb = 0, okb = 0, bfb = 0;
        ok = (oc_ab_read_flags(&nb, &okb, &bfb) == 0 &&
              nb == 0 && okb == 0);
    }
    case_result(ok);

    case_begin("set_boot(A) idempotent");
    case_result(oc_update_set_boot("A") == 0 &&
                oc_update_set_boot("A") == 0);

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_rollback_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_local_test (offline flow through cmd_update --local)           */
/* ==================================================================== */

int cmd_update_local_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_local_test] offline package flow\n");

    case_begin("A/B disk present");
    int ab = oc_ab_flags_ready();
    case_result(ab);
    if (!ab) return 1;

    const char *path = downloaded_package_path();
    case_begin("package file present");
    case_result(path != NULL);
    if (!path) {
        oc_console_puts("[update_local_test] run update_download_test "
                        "first (or place a package at /data)\n");
        return 1;
    }

    /* run the real command path */
    char cmdline[192];
    oc_strcpy(cmdline, "--local ");
    oc_strcat(cmdline, path);
    case_begin("cmd_update --local");
    int rc = cmd_update(cmdline);
    case_result(rc == 0);

    case_begin("next boot flag = B");
    int nb = 0, okb = 0, bfb = 0;
    case_result(oc_ab_read_flags(&nb, &okb, &bfb) == 0 && nb == 1);

    /* restore a neutral state for subsequent tests */
    oc_update_set_boot("A");

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_local_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* update_status_test                                                    */
/* ==================================================================== */

int cmd_update_status_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[update_status_test] status struct coverage\n");

    oc_update_status_t st;
    oc_memset(&st, 0xAA, sizeof(st));
    int rc = oc_update_get_status(&st);

    case_begin("status returns 0");
    case_result(rc == 0);

    case_begin("current_version filled");
    case_result(oc_strcmp(st.current_version,
                          OC_UPDATE_CURRENT_VERSION) == 0);

    case_begin("current_boot known (A/B/ISO)");
    case_result(oc_strcmp(st.current_boot, "A") == 0 ||
                oc_strcmp(st.current_boot, "B") == 0 ||
                oc_strcmp(st.current_boot, "ISO") == 0);

    case_begin("online_update flag 0/1");
    case_result(st.online_update == 0 || st.online_update == 1);

    case_begin("ab_present flag 0/1");
    case_result(st.ab_present == 0 || st.ab_present == 1);

    /* print the whole status for the record */
    oc_console_puts("[update_status_test] version=");
    oc_console_puts(st.current_version);
    oc_console_puts(" boot=");
    oc_console_puts(st.current_boot);
    oc_console_puts(" next=");
    oc_console_puts(st.next_boot[0] ? st.next_boot : "(default)");
    oc_console_puts(" online=");
    oc_console_puts(st.online_update ? "yes" : "no");
    oc_console_puts(" ab=");
    oc_console_puts(st.ab_present ? "yes" : "no");
    oc_console_puts("\n");

    char line[64];
    char num[12];
    oc_strcpy(line, "[update_status_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ==================================================================== */
/* real_update_test: end-to-end phase 1                                  */
/* ==================================================================== */

int cmd_real_update_test(const char *args) {
    (void)args;
    t_pass = 0; t_total = 0;
    oc_console_puts("[real_update_test] end-to-end phase 1 "
                    "(download -> install -> set_boot)\n");

    case_begin("A/B disk present");
    int ab = oc_ab_flags_ready();
    case_result(ab);
    if (!ab) return 1;

    case_begin("online_update enabled");
    int en = oc_config_online_update_enabled();
    case_result(en);
    if (!en) return 1;

    case_begin("manifest check (new version)");
    oc_update_pkg_info_t pkg;
    int rc = oc_update_check_pkg(&pkg);
    int ok = (rc == OC_UPDATE_NEW && pkg.have_package);
    case_info("rc=", rc);
    case_result(ok);
    if (!ok) return 1;

    const char *path = OC_UPDATE_PKG_PATH;
    vfs_stat_t st;
    if (vfs_stat("/data", &st) != 0) path = OC_UPDATE_PKG_TMP;

    case_begin("download");
    int n = oc_update_download(pkg.package_url, path);
    case_info("bytes=", n);
    case_result(n > 0);
    if (n <= 0) return 1;

    case_begin("verify sha256");
    rc = oc_update_verify(path, pkg.package_sha256);
    case_result(rc == 0);
    if (rc != 0) return 1;

    case_begin("install into slot B");
    rc = oc_update_install(path, "B");
    case_result(rc == 0);
    if (rc != 0) return 1;

    case_begin("set boot to B");
    rc = oc_update_set_boot("B");
    case_result(rc == 0);
    if (rc != 0) return 1;

    oc_console_puts("[real_update_test] phase 1 complete\n");
    oc_console_puts("[real_update_test] phase 2: reboot, verify slot B "
                    "kernel, then rollback\n");

    char line[64];
    char num[12];
    oc_strcpy(line, "[real_update_test] ");
    oc_u64_to_str((u64)t_pass, num);
    oc_strcat(line, num);
    oc_strcat(line, "/");
    oc_u64_to_str((u64)t_total, num);
    oc_strcat(line, num);
    oc_strcat(line, t_pass == t_total ? " PASS" : " FAIL");
    oc_console_puts(line);
    oc_console_puts("\n");
    return (t_pass == t_total) ? 0 : 1;
}

/* ---- registration ---------------------------------------------------- */

void update_test_cmds_register(void) {
    shell_register_command("update_pkg_test", cmd_update_pkg_test,
                           "gzip/DEFLATE + tar unit tests (WP-10u)");
    shell_register_command("ab_partition_test", cmd_ab_partition_test,
                           "A/B disk discovery + slots + flags (WP-10u)");
    shell_register_command("update_check_test", cmd_update_check_test,
                           "update manifest check with package fields (WP-10u)");
    shell_register_command("update_download_test", cmd_update_download_test,
                           "download the update package (WP-10u)");
    shell_register_command("update_verify_test", cmd_update_verify_test,
                           "SHA256 verification of the package (WP-10u)");
    shell_register_command("update_install_test", cmd_update_install_test,
                           "install the package into slot B (WP-10u)");
    shell_register_command("update_rollback_test", cmd_update_rollback_test,
                           "boot flags + rollback (WP-10u)");
    shell_register_command("update_local_test", cmd_update_local_test,
                           "offline update flow via cmd_update --local (WP-10u)");
    shell_register_command("update_status_test", cmd_update_status_test,
                           "oc_update_get_status coverage (WP-10u)");
    shell_register_command("real_update_test", cmd_real_update_test,
                           "end-to-end update phase 1 (WP-10u)");
}
