/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2026 cubestudio-dev <cubestudio@qq.com> */
/* Open Cube OS - WP-09 mainstream batch
 * File: kernel/x509.c
 * Purpose: X.509 v3 chain validation. Minimal but real DER walking:
 * Certificate ::= SEQUENCE { tbsCertificate, signatureAlgorithm, signature }
 * Signature algorithms: sha256WithRSA / sha384WithRSA / sha512WithRSA /
 * ecdsa-with-SHA256 / ecdsa-with-SHA384 (+ RSA-PSS with sha256 params).
 * Roots: embedded DER blobs (generated by tools/embed_roots.py).
 */
#include "x509.h"
#include "rsa.h"
#include "ec_nist.h"
#include "crypto.h"   /* sha256 */
#include "sha512.h"
#include "rtc.h"
#include "roots.h"
#include "string.h"

/* ---- signature algorithm ids ---- */
#define X509_SIG_RSA_SHA256 1
#define X509_SIG_RSA_SHA384 2
#define X509_SIG_RSA_SHA512 3
#define X509_SIG_RSA_PSS_SHA256 4
#define X509_SIG_ECDSA_SHA256 5
#define X509_SIG_ECDSA_SHA384 6

/* ---- DER walking ---- */

typedef struct {
    const u8 *p;
    int len;
} der_t;

static int der_read_tag_len(der_t *d, u8 *tag, const u8 **body, int *body_len) {
    if (d->len < 2) return -1;
    u8 t = d->p[0];
    if ((t & 0x1F) == 0x1F) return -1;        /* multi-byte tags unsupported */
    *tag = t;
    int l = d->p[1];
    int hdr = 2;
    if (l & 0x80) {
        int n = l & 0x7F;
        if (n == 0 || n > 4 || d->len < 2 + n) return -1;
        l = 0;
        for (int i = 0; i < n; i++) l = (l << 8) | d->p[2 + i];
        hdr = 2 + n;
    }
    if (d->len < hdr + l) return -1;
    *body = d->p + hdr;
    *body_len = l;
    d->p += hdr + l;
    d->len -= hdr + l;
    return 0;
}

/* Enter a constructed element: consume it from d, return a sub-der. */
static int der_enter(der_t *d, u8 expect_tag, der_t *sub) {
    u8 tag;
    const u8 *body;
    int blen;
    if (der_read_tag_len(d, &tag, &body, &blen) != 0) return -1;
    if (tag != expect_tag) return -1;
    sub->p = body;
    sub->len = blen;
    return 0;
}

/* ---- OID helpers ---- */

static const u8 OID_RSA_SHA256[] = {0x2A,0x86,0x48,0x86,0xF7,0x0D,0x01,0x01,0x0B};
static const u8 OID_RSA_SHA384[] = {0x2A,0x86,0x48,0x86,0xF7,0x0D,0x01,0x01,0x0C};
static const u8 OID_RSA_SHA512[] = {0x2A,0x86,0x48,0x86,0xF7,0x0D,0x01,0x01,0x0D};
static const u8 OID_RSA_PSS[]    = {0x2A,0x86,0x48,0x86,0xF7,0x0D,0x01,0x01,0x0A};
static const u8 OID_RSA_ENCRYPTION[] = {0x2A,0x86,0x48,0x86,0xF7,0x0D,0x01,0x01,0x01};
static const u8 OID_EC_PUBLIC_KEY[]  = {0x2A,0x86,0x48,0xCE,0x3D,0x02,0x01};
static const u8 OID_EC_SECP256R1[]   = {0x2A,0x86,0x48,0xCE,0x3D,0x03,0x01,0x07};
static const u8 OID_EC_SECP384R1[]   = {0x2B,0x81,0x04,0x00,0x22};
static const u8 OID_ECDSA_SHA256[]   = {0x2A,0x86,0x48,0xCE,0x3D,0x04,0x03,0x02};
static const u8 OID_ECDSA_SHA384[]   = {0x2A,0x86,0x48,0xCE,0x3D,0x04,0x03,0x03};
static const u8 OID_CN[]             = {0x55,0x04,0x03};
static const u8 OID_SAN[]            = {0x55,0x1D,0x11};
static const u8 OID_BASIC_CONSTRAINTS[] = {0x55,0x1D,0x13};

static int oid_is(const u8 *oid, int oid_len, const u8 *want, int want_len) {
    return oid_len == want_len && oc_memcmp(oid, want, want_len) == 0;
}

/* ---- validity time parsing ---- */

static int two_digits(const u8 *p) {
    if (p[0] < '0' || p[0] > '9' || p[1] < '0' || p[1] > '9') return -1;
    return (p[0] - '0') * 10 + (p[1] - '0');
}

static u64 x509_time_to_unix(const u8 *p, int len) {
    /* UTCTime: YYMMDDHHMMSSZ (13) — GeneralizedTime: YYYYMMDDHHMMSSZ (15) */
    int year, mon, day, hour, min, sec;
    if (len >= 13 && p[len - 1] == 'Z' && p[0] >= '0' && p[0] <= '9'
        && len == 13) {
        int yy = two_digits(p);
        mon = two_digits(p + 2);
        day = two_digits(p + 4);
        hour = two_digits(p + 6);
        min = two_digits(p + 8);
        sec = two_digits(p + 10);
        year = (yy < 50) ? 2000 + yy : 1900 + yy;
        if (mon < 1 || mon > 12 || day < 1 || day > 31) return 0;
        goto have;
    }
    if (len >= 15 && p[len - 1] == 'Z') {
        year = two_digits(p) * 100 + two_digits(p + 2);
        mon = two_digits(p + 4);
        day = two_digits(p + 6);
        hour = two_digits(p + 8);
        min = two_digits(p + 10);
        sec = two_digits(p + 12);
        if (mon < 1 || mon > 12 || day < 1 || day > 31) return 0;
        goto have;
    }
    return 0;
have:
    {
        /* days since epoch (simplified civil algorithm) */
        int y = year;
        y -= mon <= 2;
        long long era = (y >= 0 ? y : y - 399) / 400;
        unsigned yoe = (unsigned)(y - era * 400);
        unsigned doy = (153 * (unsigned)(mon + (mon > 2 ? -3 : 9)) + 2) / 5
                       + (unsigned)day - 1;
        unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
        long long days = era * 146097 + (long long)doe - 719468;
        return (u64)days * 86400ULL
             + (u64)hour * 3600 + (u64)min * 60 + (u64)sec;
    }
}

/* ---- name (RDN sequence) → printable string (CN + O fallbacks) ---- */

static int parse_name(der_t *d, char *out, int out_size) {
    /* Name ::= RDNSequence ::= SEQUENCE OF RelativeDistinguishedName */
    der_t seq;
    if (der_enter(d, 0x30, &seq) != 0) return -1;
    out[0] = 0;
    int wrote = 0;
    while (seq.len > 0 && wrote < out_size - 1) {
        der_t rdn;
        if (der_enter(&seq, 0x31, &rdn) != 0) return -1;
        while (rdn.len > 0) {
            der_t atv;
            u8 tag;
            const u8 *body;
            int blen;
            if (der_enter(&rdn, 0x30, &atv) != 0) return -1;
            /* AttributeTypeAndValue: SEQUENCE { OID, value } */
            if (der_read_tag_len(&atv, &tag, &body, &blen) != 0 || tag != 0x06)
                return -1;
            int is_cn = oid_is(body, blen, OID_CN, sizeof(OID_CN));
            if (der_read_tag_len(&atv, &tag, &body, &blen) != 0) return -1;
            if (is_cn && blen > 0 && blen < out_size - 1 - wrote) {
                oc_memcpy(out + wrote, body, blen);
                wrote += blen;
                out[wrote] = 0;
            }
        }
    }
    return 0;
}

/* ---- certificate parse ---- */

int x509_parse(x509_cert_t *c, const u8 *der, int der_len) {
    oc_memset(c, 0, sizeof(*c));
    c->der = der;
    c->der_len = der_len;

    der_t d = { der, der_len };
    der_t cert, tbs, sigalg;
    if (der_enter(&d, 0x30, &cert) != 0) return X509_E_FORMAT;
    if (cert.len != d.p - (der)) { /* allow trailing padding; not enforced */ }
    if (der_enter(&cert, 0x30, &tbs) != 0) return X509_E_FORMAT;
    c->sig_input = tbs.p - 4;    /* SEQUENCE header included */
    c->sig_input_len = tbs.len + 4;
    if (der_enter(&cert, 0x30, &sigalg) != 0) return X509_E_FORMAT;
    {
        u8 tag;
        const u8 *body;
        int blen;
        der_t sa = sigalg;
        if (der_read_tag_len(&sa, &tag, &body, &blen) != 0 || tag != 0x06)
            return X509_E_FORMAT;
        if (oid_is(body, blen, OID_RSA_SHA256, sizeof(OID_RSA_SHA256)))
            c->sig_alg = X509_SIG_RSA_SHA256;
        else if (oid_is(body, blen, OID_RSA_SHA384, sizeof(OID_RSA_SHA384)))
            c->sig_alg = X509_SIG_RSA_SHA384;
        else if (oid_is(body, blen, OID_RSA_SHA512, sizeof(OID_RSA_SHA512)))
            c->sig_alg = X509_SIG_RSA_SHA512;
        else if (oid_is(body, blen, OID_RSA_PSS, sizeof(OID_RSA_PSS)))
            c->sig_alg = X509_SIG_RSA_PSS_SHA256;
        else if (oid_is(body, blen, OID_ECDSA_SHA256, sizeof(OID_ECDSA_SHA256)))
            c->sig_alg = X509_SIG_ECDSA_SHA256;
        else if (oid_is(body, blen, OID_ECDSA_SHA384, sizeof(OID_ECDSA_SHA384)))
            c->sig_alg = X509_SIG_ECDSA_SHA384;
        else
            return X509_E_UNSUPPORTED;
    }
    {
        u8 tag;
        const u8 *body;
        int blen;
        der_t rest = cert;
        if (der_read_tag_len(&rest, &tag, &body, &blen) != 0 || tag != 0x03)
            return X509_E_FORMAT;
        if (blen < 1 || body[0] != 0x00) return X509_E_FORMAT;
        c->sig = body + 1;
        c->sig_len = blen - 1;
    }

    /* ---- TBSCertificate ---- */
    u8 tag;
    const u8 *body;
    int blen;
    der_t t = tbs;

    /* version [0] EXPLICIT (optional) */
    if (t.len > 0 && t.p[0] == 0xA0) {
        if (der_read_tag_len(&t, &tag, &body, &blen) != 0) return X509_E_FORMAT;
    }
    /* serialNumber */
    if (der_read_tag_len(&t, &tag, &body, &blen) != 0 || tag != 0x02)
        return X509_E_FORMAT;
    /* signature algorithm (inner) — skip */
    if (der_enter(&t, 0x30, &sigalg) != 0) return X509_E_FORMAT;
    /* issuer */
    if (parse_name(&t, c->issuer, X509_MAX_NAME) != 0) return X509_E_FORMAT;
    /* validity */
    der_t validity;
    if (der_enter(&t, 0x30, &validity) != 0) return X509_E_FORMAT;
    {
        u8 vtag;
        const u8 *vbody;
        int vlen;
        if (der_read_tag_len(&validity, &vtag, &vbody, &vlen) != 0)
            return X509_E_FORMAT;
        c->not_before = x509_time_to_unix(vbody, vlen);
        if (der_read_tag_len(&validity, &vtag, &vbody, &vlen) != 0)
            return X509_E_FORMAT;
        c->not_after = x509_time_to_unix(vbody, vlen);
        if (c->not_before == 0 || c->not_after == 0) return X509_E_FORMAT;
    }
    /* subject */
    if (parse_name(&t, c->subject, X509_MAX_NAME) != 0) return X509_E_FORMAT;
    /* subjectPublicKeyInfo */
    {
        der_t spki;
        if (der_enter(&t, 0x30, &spki) != 0) return X509_E_FORMAT;
        /* re-read from tbs for the raw bytes */
        /* spki starts 4 bytes before spki.p (header) */
        c->spki = spki.p - 4;
        c->spki_len = spki.len + 4;
        der_t alg;
        if (der_enter(&spki, 0x30, &alg) != 0) return X509_E_FORMAT;
        u8 otag;
        const u8 *obody;
        int olen;
        if (der_read_tag_len(&alg, &otag, &obody, &olen) != 0 || otag != 0x06)
            return X509_E_FORMAT;
        if (oid_is(obody, olen, OID_RSA_ENCRYPTION,
                   sizeof(OID_RSA_ENCRYPTION))) {
            /* RSA: BIT STRING wraps DER SEQUENCE(n, e) */
            u8 btag;
            const u8 *bbody;
            int blen2;
            if (der_read_tag_len(&spki, &btag, &bbody, &blen2) != 0
                || btag != 0x03 || blen2 < 1)
                return X509_E_FORMAT;
            der_t rsad = { bbody + 1, blen2 - 1 };
            der_t seq;
            if (der_enter(&rsad, 0x30, &seq) != 0) return X509_E_FORMAT;
            u8 itag;
            const u8 *ibody;
            int ilen;
            if (der_read_tag_len(&seq, &itag, &ibody, &ilen) != 0
                || itag != 0x02) return X509_E_FORMAT;
            c->rsa_n = ibody;
            c->rsa_n_len = ilen;
            if (der_read_tag_len(&seq, &itag, &ibody, &ilen) != 0
                || itag != 0x02) return X509_E_FORMAT;
            c->rsa_e = ibody;
            c->rsa_e_len = ilen;
            /* strip leading zero for uniform compare (keep value) */
            while (c->rsa_n_len > 1 && c->rsa_n[0] == 0) {
                c->rsa_n++;
                c->rsa_n_len--;
            }
            while (c->rsa_e_len > 1 && c->rsa_e[0] == 0) {
                c->rsa_e++;
                c->rsa_e_len--;
            }
        } else if (oid_is(obody, olen, OID_EC_PUBLIC_KEY,
                          sizeof(OID_EC_PUBLIC_KEY))) {
            /* curve OID inside alg params */
            u8 ctag;
            const u8 *cbody;
            int clen;
            if (der_read_tag_len(&alg, &ctag, &cbody, &clen) != 0
                || ctag != 0x06) return X509_E_FORMAT;
            if (oid_is(cbody, clen, OID_EC_SECP256R1,
                       sizeof(OID_EC_SECP256R1))) c->ec_curve = EC_P256;
            else if (oid_is(cbody, clen, OID_EC_SECP384R1,
                            sizeof(OID_EC_SECP384R1))) c->ec_curve = EC_P384;
            else return X509_E_UNSUPPORTED;
            u8 btag;
            const u8 *bbody;
            int blen2;
            if (der_read_tag_len(&spki, &btag, &bbody, &blen2) != 0
                || btag != 0x03 || blen2 < 2) return X509_E_FORMAT;
            if (blen2 - 1 > (int)sizeof(c->ec_pub)) return X509_E_FORMAT;
            oc_memcpy(c->ec_pub, bbody + 1, blen2 - 1);
            c->ec_pub_len = blen2 - 1;
        } else {
            return X509_E_UNSUPPORTED;
        }
    }
    /* issuerUniqueID [1] / subjectUniqueID [2] / extensions [3] */
    while (t.len > 0) {
        u8 xtag;
        const u8 *xbody;
        int xlen;
        if (der_read_tag_len(&t, &xtag, &xbody, &xlen) != 0) break;
        if (xtag != 0xA3) continue;   /* [3] EXPLICIT extensions */
        der_t exts = { xbody, xlen };
        der_t seq;
        if (der_enter(&exts, 0x30, &seq) != 0) return X509_E_FORMAT;
        while (seq.len > 0) {
            der_t ext;
            if (der_enter(&seq, 0x30, &ext) != 0) break;
            u8 etag;
            const u8 *ebody;
            int elen;
            if (der_read_tag_len(&ext, &etag, &ebody, &elen) != 0
                || etag != 0x06) break;
            int is_san = oid_is(ebody, elen, OID_SAN, sizeof(OID_SAN));
            int is_bc = oid_is(ebody, elen, OID_BASIC_CONSTRAINTS,
                               sizeof(OID_BASIC_CONSTRAINTS));
            if (!is_san && !is_bc) continue;
            /* Extension ::= SEQUENCE { extnID, critical BOOLEAN DEFAULT
             * FALSE, extnValue OCTET STRING } — the criticality flag must
             * be checked BEFORE consuming the value element. */
            int critical = 0;
            if (ext.len > 0 && ext.p[0] == 0x01) {
                u8 ctag;
                const u8 *cbody;
                int clen;
                if (der_read_tag_len(&ext, &ctag, &cbody, &clen) != 0) break;
                critical = clen > 0 && cbody[0];
            }
            (void)critical;
            u8 vtag;
            const u8 *vbody;
            int vlen;
            if (der_read_tag_len(&ext, &vtag, &vbody, &vlen) != 0
                || vtag != 0x04) break;
            if (is_bc) {
                /* BasicConstraints ::= SEQUENCE { cA BOOLEAN DEFAULT FALSE } */
                der_t bc = { vbody, vlen };
                der_t seq2;
                if (der_enter(&bc, 0x30, &seq2) != 0) continue;
                if (seq2.len > 0 && seq2.p[0] == 0x01) {
                    u8 b2t;
                    const u8 *b2b;
                    int b2l;
                    if (der_read_tag_len(&seq2, &b2t, &b2b, &b2l) != 0) continue;
                    c->is_ca = b2l > 0 && b2b[0];
                }
            } else {
                /* SAN ::= SEQUENCE OF GeneralName; dNSName = [2] IA5String */
                der_t san = { vbody, vlen };
                der_t sseq;
                if (der_enter(&san, 0x30, &sseq) != 0) continue;
                while (sseq.len > 0 && c->dns_count < X509_MAX_DNS) {
                    u8 gtag;
                    const u8 *gbody;
                    int glen;
                    if (der_read_tag_len(&sseq, &gtag, &gbody, &glen) != 0)
                        break;
                    if ((gtag & 0x8F) != 0x82) continue;   /* context [2] */
                    if (glen <= 0 || glen >= X509_MAX_NAME) continue;
                    oc_memcpy(c->dns_names[c->dns_count], gbody, glen);
                    c->dns_names[c->dns_count][glen] = 0;
                    c->dns_count++;
                }
            }
        }
    }
    return X509_OK;
}

/* ---- hostname matching ---- */

static int host_match(const char *pattern, const char *host) {
    int plen = (int)oc_strlen(pattern);
    int hlen = (int)oc_strlen(host);
    if (plen == 0 || hlen == 0) return 0;
    /* wildcard: only "*.example.com" form (single left label) */
    if (plen > 2 && pattern[0] == '*' && pattern[1] == '.') {
        const char *dot = host;
        while (*dot && *dot != '.') dot++;
        if (*dot != '.') return 0;
        return oc_strcmp(pattern + 1, dot) == 0;
    }
    if (plen != hlen) return 0;
    for (int i = 0; i < plen; i++) {
        char a = pattern[i], b = host[i];
        if (a >= 'A' && a <= 'Z') a = (char)(a - 'A' + 'a');
        if (b >= 'A' && b <= 'Z') b = (char)(b - 'A' + 'a');
        if (a != b) return 0;
    }
    return 1;
}

/* ---- signature verification of one certificate with an issuer key ---- */

static int verify_cert_sig(const x509_cert_t *crt, const x509_cert_t *issuer) {
    u8 hash[64];
    int hlen;
    int sha_alg;
    switch (crt->sig_alg) {
        case X509_SIG_RSA_SHA256:
        case X509_SIG_ECDSA_SHA256:
        case X509_SIG_RSA_PSS_SHA256:
            sha256(crt->sig_input, crt->sig_input_len, hash);
            hlen = 32; sha_alg = RSA_SHA256; break;
        case X509_SIG_RSA_SHA384:
        case X509_SIG_ECDSA_SHA384:
            sha384(crt->sig_input, crt->sig_input_len, hash);
            hlen = 48; sha_alg = RSA_SHA384; break;
        case X509_SIG_RSA_SHA512:
            sha512(crt->sig_input, crt->sig_input_len, hash);
            hlen = 64; sha_alg = RSA_SHA512; break;
        default:
            return X509_E_UNSUPPORTED;
    }
    if (crt->sig_alg == X509_SIG_ECDSA_SHA256
        || crt->sig_alg == X509_SIG_ECDSA_SHA384) {
        /* ECDSA sig is a DER SEQUENCE of two INTEGERs; decode r/s */
        der_t d = { crt->sig, crt->sig_len };
        der_t seq, inner;
        if (der_enter(&d, 0x30, &seq) != 0) return X509_E_BADSIG;
        inner = seq;
        u8 tag;
        const u8 *body;
        int blen;
        if (der_read_tag_len(&inner, &tag, &body, &blen) != 0 || tag != 0x02)
            return X509_E_BADSIG;
        u8 r[EC_MAX_SCALAR];
        int rlen = blen;
        while (rlen > 1 && body[0] == 0) { body++; rlen--; }
        if (rlen > hlen) return X509_E_BADSIG;
        oc_memcpy(r + (hlen - rlen), body, rlen);
        if (der_read_tag_len(&inner, &tag, &body, &blen) != 0 || tag != 0x02)
            return X509_E_BADSIG;
        u8 s[EC_MAX_SCALAR];
        int slen = blen;
        while (slen > 1 && body[0] == 0) { body++; slen--; }
        if (slen > hlen) return X509_E_BADSIG;
        oc_memcpy(s + (hlen - slen), body, slen);
        int curve = (crt->sig_alg == X509_SIG_ECDSA_SHA256) ? EC_P256 : EC_P384;
        if (issuer->ec_curve != curve) return X509_E_BADSIG;
        return ecdsa_verify(curve, issuer->ec_pub, issuer->ec_pub_len,
                            hash, hlen, r, hlen, s, hlen) == 1
                   ? X509_OK : X509_E_BADSIG;
    }
    /* RSA-based */
    if (issuer->rsa_n == 0) return X509_E_BADSIG;
    if (crt->sig_alg == X509_SIG_RSA_PSS_SHA256) {
        /* PSS signature is OCTET STRING wrapped */
        return rsa_verify_pss(issuer->rsa_n, issuer->rsa_n_len,
                              issuer->rsa_e, issuer->rsa_e_len,
                              RSA_SHA256, hash, hlen,
                              crt->sig, crt->sig_len) == 1
                   ? X509_OK : X509_E_BADSIG;
    }
    return rsa_verify_pkcs1(issuer->rsa_n, issuer->rsa_n_len,
                            issuer->rsa_e, issuer->rsa_e_len,
                            sha_alg, hash, hlen,
                            crt->sig, crt->sig_len) == 1
               ? X509_OK : X509_E_BADSIG;
}

/* issuer name == subject name of the issuing cert (byte compare) */
static int same_name(const char *a, const char *b) {
    return oc_strcmp(a, b) == 0;
}

int x509_verify_chain(const x509_cert_t *chain, int chain_len,
                      const char *hostname) {
    if (chain_len <= 0) return X509_E_FORMAT;
    u64 now = rtc_unix_now();
    if (now < chain[0].not_before) return X509_E_NOT_YET;
    if (now > chain[0].not_after) return X509_E_EXPIRED;

    /* hostname check on the leaf */
    if (hostname) {
        int ok = 0;
        for (int i = 0; i < chain[0].dns_count && !ok; i++)
            ok = host_match(chain[0].dns_names[i], hostname);
        if (!ok) return X509_E_HOSTNAME;
    }

    for (int i = 0; i < chain_len; i++) {
        const x509_cert_t *crt = &chain[i];
        if (now < crt->not_before) return X509_E_NOT_YET;
        if (now > crt->not_after) return X509_E_EXPIRED;

        /* Trust-anchor check: if this certificate IS a root in the store
         * (same subject AND same public key), the chain anchors here.
         * This handles cross-signed intermediates whose parents use
         * algorithms we do not verify (e.g. SHA-1 self-signatures). */
        for (int r = 0; r < OC_ROOT_COUNT; r++) {
            x509_cert_t root;
            if (x509_parse(&root, oc_roots[r].der, oc_roots[r].len) != 0)
                continue;
            if (same_name(crt->subject, root.subject)
                && crt->spki_len == root.spki_len
                && oc_memcmp(crt->spki, root.spki, root.spki_len) == 0) {
                return X509_OK;
            }
        }

        /* find the issuer: next cert in the chain or a root */
        const x509_cert_t *issuer = 0;
        int anchored = 0;   /* verified directly against an embedded root */
        if (i + 1 < chain_len && same_name(crt->issuer, chain[i + 1].subject))
            issuer = &chain[i + 1];
        else {
            for (int r = 0; r < OC_ROOT_COUNT; r++) {
                x509_cert_t root;
                if (x509_parse(&root, oc_roots[r].der, oc_roots[r].len) != 0)
                    continue;
                if (same_name(crt->issuer, root.subject)) {
                    issuer = &root;
                    anchored = 1;
                    break;
                }
            }
        }
        if (!issuer) return X509_E_NO_ISSUER;
        if (verify_cert_sig(crt, issuer) != X509_OK) return X509_E_BADSIG;
        if (anchored) return X509_OK;   /* chain reached a trusted root key */
        /* issuers beyond a self-signed root must be CAs */
        if (i + 1 < chain_len && !issuer->is_ca) return X509_E_BADSIG;
    }
    /* walked the whole chain without anchoring at a root */
    return X509_E_NO_ROOT;
}

const char *x509_errstr(int code) {
    switch (code) {
        case X509_OK: return "OK";
        case X509_E_FORMAT: return "bad certificate format";
        case X509_E_UNSUPPORTED: return "unsupported algorithm";
        case X509_E_EXPIRED: return "certificate expired";
        case X509_E_NOT_YET: return "certificate not yet valid";
        case X509_E_NO_ROOT: return "no trusted root found";
        case X509_E_BADSIG: return "signature verification failed";
        case X509_E_HOSTNAME: return "hostname mismatch";
        case X509_E_NO_ISSUER: return "issuer certificate missing";
    }
    return "unknown error";
}
