#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 cubestudio-dev <cubestudio@qq.com>
"""
build_solib.py: Compile a shared-library userprog source (userprogs/libfoo.c)
into an ET_DYN shared object built with -Wl,-soname,<name>.so, then refresh
its byte array in l1/solib_data.h.

Usage: python3 tools/build_solib.py [c_file]
       (default: userprogs/libfoo.c)

The embed chain previously mishandled libfoo.c: it is a shared library, but
the Makefile routed it through build_c_userprog.py (an ET_EXEC user-program
recipe), which failed with
    ERROR: userprog_libfoo block not found in kernel/core/userprogs_data.h
because libfoo's blob lives in l1/solib_data.h under the solib_libfoo name.
This script is the correct solib leg of the embed chain.
"""
import os
import re
import struct
import subprocess
import sys

DT_SONAME = 14
ET_DYN = 3


def fail(msg):
    print(f"build_solib: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def parse_soname(data):
    """Extract DT_SONAME string from an ELF64 shared object."""
    if len(data) < 64 or data[:4] != b"\x7fELF":
        fail("not an ELF file")
    e_type = struct.unpack_from("<H", data, 16)[0]
    if e_type != ET_DYN:
        fail(f"e_type is {e_type}, expected ET_DYN (3) for a shared object")
    e_shoff, = struct.unpack_from("<Q", data, 40)
    e_shentsize, e_shnum = struct.unpack_from("<HH", data, 58)
    dyn_sec = dynstr_sec = None
    for i in range(e_shnum):
        off = e_shoff + i * e_shentsize
        sh_type, = struct.unpack_from("<I", data, off + 4)
        if sh_type == 6:      # SHT_DYNAMIC
            dyn_sec = off
        elif sh_type == 3:    # SHT_STRTAB candidate (.dynstr found via link)
            pass
    if dyn_sec is None:
        fail("no SHT_DYNAMIC section (not a shared object?)")
    dyn_link, = struct.unpack_from("<I", data, dyn_sec + 40)  # sh_link -> .dynstr
    dyn_offset, dyn_size = struct.unpack_from("<QQ", data, dyn_sec + 24)
    str_off = e_shoff + dyn_link * e_shentsize
    str_offset, = struct.unpack_from("<Q", data, str_off + 24)
    soname = None
    for i in range(dyn_size // 16):
        d_tag, d_val = struct.unpack_from("<qQ", data, dyn_offset + i * 16)
        if d_tag == 0:
            break
        if d_tag == DT_SONAME:
            end = data.index(b"\x00", str_offset + d_val)
            soname = data[str_offset + d_val:end].decode()
    return soname


def main():
    _ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(_ROOT, "userprogs", "libfoo.c")
    if not os.path.exists(src):
        fail(f"source not found: {src}")
    name = os.path.splitext(os.path.basename(src))[0]
    soname = f"{name}.so"
    build_dir = os.path.join(_ROOT, "build")
    os.makedirs(build_dir, exist_ok=True)
    obj_path = os.path.join(build_dir, f"{name}_solib.o")
    so_path = os.path.join(build_dir, f"{name}.so")
    cc = os.environ.get("CC", "/usr/bin/gcc")

    r = subprocess.run(
        [cc, "-ffreestanding", "-fno-stack-protector", "-fPIC",
         "-mno-red-zone", "-mno-sse", "-mno-mmx", "-mno-3dnow",
         "-fno-asynchronous-unwind-tables", "-Wall", "-Wextra",
         "-O2", "-std=gnu11", "-c", src, "-o", obj_path],
        capture_output=True, text=True)
    if r.returncode != 0:
        fail(f"CC error:\n{r.stderr}")

    # SONAME is mandatory: ld.so's DT_NEEDED lookup and the kernel-side
    # solib table both key on "libfoo.so" (set via -Wl,-soname).
    r = subprocess.run(
        [cc, "-shared", "-nostdlib", "-Wl,-soname," + soname,
         "-z", "max-page-size=0x1000", "-z", "noexecstack",
         "-o", so_path, obj_path],
        capture_output=True, text=True)
    if r.returncode != 0:
        fail(f"LD error:\n{r.stderr}")

    with open(so_path, "rb") as f:
        data = f.read()
    actual_soname = parse_soname(data)
    if actual_soname != soname:
        fail(f"DT_SONAME is {actual_soname!r}, expected {soname!r}")
    print(f"build_solib: {name} = {len(data)} bytes from {so_path} "
          f"(ET_DYN, DT_SONAME={soname})")

    hex_lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(data) else ""
        hex_lines.append(f"    {hex_vals}{comma}")
    header = (
        "/* SPDX-License-Identifier: Apache-2.0 */\n"
        "/* Copyright 2026 cubestudio-dev <cubestudio@qq.com> */\n"
        "/* Auto-generated - DO NOT EDIT. */\n"
        "\n"
        '#include "types.h"\n'
        "\n"
        f"/* WP-08b Batch 5: embedded shared library {soname}. {len(data)} bytes.\n"
        " * ET_DYN shared object. Regenerated by tools/build_solib.py\n"
        " * (compile -fPIC, link -shared -Wl,-soname). Kernel maps this to\n"
        " * SOLIB_LIBFOO_BASE (0x30000000) for DT_NEEDED programs, and via\n"
        " * SYS_MAP_SOLIB (90) for dlopen() at runtime. */\n"
    )
    content = (header
               + f"const u8 solib_{name}[] = {{\n"
               + "\n".join(hex_lines) + "\n};\n"
               + f"const u64 solib_{name}_size = {len(data)};\n")
    header_path = os.path.join(_ROOT, "l1", "solib_data.h")
    with open(header_path, "w") as f:
        f.write(content)
    print(f"  regenerated solib_{name} block in {header_path}")


if __name__ == "__main__":
    main()
