#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 cubestudio-dev <cubestudio@qq.com>
"""WP-10d-pre: build-time generator for kernel/generated/grub_boot_data.c.

Rule-9 ("system self-sufficiency") fix: the abdisk / install / grub-install
shell commands need a BIOS boot loader *inside* the kernel so a user can
partition a disk, install the system and make it bootable without leaving
the OS shell.  This script is the build-time half of that:

  1. boot.img   - copied from the GRUB 2.12 i386-pc install (512 bytes).
  2. core.img   - produced by grub-mkimage with every module the on-disk
                  grub.cfg needs (BIOS disk, partition tables, FAT, the
                  multiboot2 loader, search, serial console, ...), plus an
                  embedded early config that finds /boot/grub/grub.cfg.

The kernel ELF payload is NOT embedded: the grub.cfg files attach the
booting kernel itself as a multiboot2 module ("module2 ... self"), and
the kernel copies that module onto the target disk - the mainstream
installer pattern (take the payload from the boot media), which also
keeps the kernel small.

Usage (called by the Makefile):
  python3 tools/embed_grub.py <OC_TOOLS> <base-elf> <out-c-file>
"""

import os
import subprocess
import sys

EARLY_CFG = """\
search --file --set=root /boot/grub/grub.cfg
if [ "$root" = "(memdisk)" ]; then set root=(hd0,msdos1); fi
set prefix=($root)/boot/grub
normal
"""

GRUB_MODULES = [
    "biosdisk",       # INT 13h disk access
    "part_msdos",     # MBR partition tables
    "part_gpt",       # GPT partition tables
    "fat",            # FAT32 (system + A/B slot partitions)
    "multiboot2",     # our kernel boot protocol
    "search",         # the search command itself
    "search_fs_file", # find the partition holding /boot/grub/grub.cfg
    "normal",         # the menu engine (reads grub.cfg)
    "configfile",     # config file sourcing
    "echo",           # BOOT_SLOT banner
    "serial",         # serial console (grub.cfg terminal_output)
    "test",           # [ -f ... ] flag-file checks in grub.cfg
    "ls",             # rescue debugging
]

C_HEADER = """\
/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2026 cubestudio-dev <cubestudio@qq.com> */
/*
 * Open Cube OS - WP-10d-pre (rule-9 system self-sufficiency fix)
 * File: kernel/generated/grub_boot_data.c  -- BUILD-TIME GENERATED.
 *
 * Generated by tools/embed_grub.py from:
 *   - GRUB 2.12 i386-pc boot.img (MBR boot code template)
 *   - a grub-mkimage core.img (biosdisk + part_msdos + part_gpt + fat +
 *     multiboot2 + search_fs_file + normal + configfile + echo + serial
 *     + test + ls, plus an embedded early config that searches for
 *     /boot/grub/grub.cfg)
 *   - the just-built kernel ELF (opencube_base.elf)
 *
 * Consumed by drivers/block/driver_block_disk_setup.c: grub-install / abdisk / install
 * write these bytes onto the target disk so the OS can partition, format
 * and make bootable a disk entirely from the oc> shell.
 *
 * DO NOT EDIT - generated file (excluded from the source distribution).
 */
#include "grub_boot_data.h"

"""


def c_array(name: str, data: bytes) -> str:
    lines = [f"const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: embed_grub.py <OC_TOOLS> <base-elf> <out-c>", file=sys.stderr)
        return 2
    oc_tools, base_elf, out_c = sys.argv[1], sys.argv[2], sys.argv[3]

    moddir = os.path.join(oc_tools, "usr", "lib", "grub", "i386-pc")
    grub_mkimage = os.path.join(oc_tools, "usr", "bin", "grub-mkimage")
    for p in (os.path.join(moddir, "boot.img"), grub_mkimage, base_elf):
        if not os.path.exists(p):
            print(f"embed_grub: missing {p}", file=sys.stderr)
            return 1

    with open(os.path.join(moddir, "boot.img"), "rb") as f:
        boot_img = f.read()
    if len(boot_img) != 512:
        print(f"embed_grub: boot.img is {len(boot_img)} bytes, expected 512",
              file=sys.stderr)
        return 1

    import tempfile
    with tempfile.TemporaryDirectory() as td:
        cfg_path = os.path.join(td, "early.cfg")
        core_path = os.path.join(td, "core.img")
        with open(cfg_path, "w") as f:
            f.write(EARLY_CFG)
        cmd = [grub_mkimage, "-O", "i386-pc", "-d", moddir,
               "-o", core_path, "-c", cfg_path,
               "-p", "(memdisk)/boot/grub"] + GRUB_MODULES
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print("embed_grub: grub-mkimage failed:\n" + res.stdout + res.stderr,
                  file=sys.stderr)
            return 1
        with open(core_path, "rb") as f:
            core_img = f.read()

    os.makedirs(os.path.dirname(out_c), exist_ok=True)
    with open(out_c, "w") as f:
        f.write(C_HEADER)
        f.write(c_array("grub_boot_img", boot_img) + "\n\n")
        f.write(c_array("grub_core_img", core_img) + "\n")
        f.write(
            f"\nconst unsigned int grub_boot_img_len = {len(boot_img)};\n"
            f"const unsigned int grub_core_img_len = {len(core_img)};\n")

    print(f"embed_grub: boot={len(boot_img)}B core={len(core_img)}B -> {out_c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
