#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 cubestudio-dev <cubestudio@qq.com>
"""Embed the major public CA roots into kernel/roots.h as DER byte arrays.

The set covers the roots needed to verify github.io / google.com /
cloudflare.com and the most common other chains (Let's Encrypt ISRG X1,
Google Trust Services GTS R1/R4, GlobalSign, DigiCert, Baltimore,
Amazon, Microsoft)."""
import os
import sys

ROOTS = [
    ("ISRG Root X1", "ISRG_Root_X1.pem"),
    ("ISRG Root X2", "ISRG_Root_X2.pem"),
    ("GlobalSign Root CA", "GlobalSign_Root_CA.pem"),
    ("GTS Root R1", "GTS_Root_R1.pem"),
    ("GTS Root R4", "GTS_Root_R4.pem"),
    ("DigiCert Global Root CA", "DigiCert_Global_Root_CA.pem"),
    ("DigiCert Global Root G2", "DigiCert_Global_Root_G2.pem"),
    ("Baltimore CyberTrust Root", "Baltimore_CyberTrust_Root.pem"),
    ("Amazon Root CA 1", "Amazon_Root_CA_1.pem"),
    ("Microsoft RSA Root CA 2017", "Microsoft_RSA_Root_Certificate_Authority_2017.pem"),
]

STORE = sys.argv[1] if len(sys.argv) > 1 else "/etc/ssl/certs"
OUT = sys.argv[2] if len(sys.argv) > 2 else "kernel/roots.h"

def pem_to_der(path):
    b64 = []
    for line in open(path):
        line = line.strip()
        if line.startswith("-----") or not line:
            continue
        b64.append(line)
    import base64
    return base64.b64decode("".join(b64))

lines = [
    "/* SPDX-License-Identifier: Apache-2.0 */",
    "/* Copyright 2026 cubestudio-dev <cubestudio@qq.com> */",
    "/* Auto-generated by tools/embed_roots.py — DO NOT EDIT BY HAND.",
    " * Embedded root CA store (DER) for the X.509 chain validator. */",
    "#ifndef OC_ROOTS_H",
    "#define OC_ROOTS_H",
    "",
    "#include \"types.h\"",
    "",
    "typedef struct {",
    "    const char *name;",
    "    const u8 *der;",
    "    int len;",
    "} oc_root_t;",
    "",
]
total = 0
for name, fname in ROOTS:
    path = os.path.join(STORE, fname)
    if not os.path.exists(path):
        print(f"skip missing {fname}", file=sys.stderr)
        continue
    der = pem_to_der(path)
    total += len(der)
    sym = ("root_" + name.lower().replace(" ", "_").replace("-", "_")
           .replace(".", "_"))
    lines.append(f"static const u8 {sym}[] = {{")
    for i in range(0, len(der), 16):
        chunk = der[i:i+16]
        lines.append("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
lines.append("#define OC_ROOT_COUNT %d" % sum(1 for l in lines if l.startswith("static const u8 root_")))
lines.append("")
lines.append("static const oc_root_t oc_roots[] = {")
for name, fname in ROOTS:
    path = os.path.join(STORE, fname)
    if not os.path.exists(path):
        continue
    sym = ("root_" + name.lower().replace(" ", "_").replace("-", "_")
           .replace(".", "_"))
    lines.append('    { "%s", %s, (int)sizeof(%s) },' % (name, sym, sym))
lines.append("};")
lines.append("")
lines.append("#endif /* OC_ROOTS_H */")
open(OUT, "w").write("\n".join(lines) + "\n")
print(f"wrote {OUT}: {len(ROOTS)} roots, {total} bytes")
